FROM centos:7
MAINTAINER pigyang <372282766@qq.com>


RUN yum install wget -y \
    && cd /root \
    && wget https://github.com/kubernetes-incubator/kompose/releases/download/v0.7.0/kompose-linux-amd64.tar.gz \
    && wget https://github.com/docker/compose/releases/download/1.14.0/docker-compose-Linux-x86_64
